## Analyze Nobel Prize winner data and identify patterns by answering the following questions:

#### What is the most commonly awarded gender and birth country?
Store your answers as string variables **top_gender** and **top_country**.

#### Which decade had the highest ratio of US-born Nobel Prize winners to total winners in all categories?
Store this as an integer called **max_decade_usa**.

#### Which decade and Nobel Prize category combination had the highest proportion of female laureates?
Store this as a dictionary called **max_female_dict** where the decade is the key and the category is the value. There should only be one key:value pair.

#### Who was the first woman to receive a Nobel Prize, and in what category?
Save your string answers as **first_woman_name** and **first_woman_category**.

#### Which individuals or organizations have won more than one Nobel Prize throughout the years?
Store the full names in a list named **repeat_list**.

In [2]:
# Loading required libraries
import pandas as pd
import seaborn as sns
import numpy as np

# Reading csv 
nobel = pd.read_csv("nobel.csv")
nobel.head()

,year,category,prize,motivation,prize_share,laureate_id,laureate_type,full_name,birth_date,birth_city,birth_country,sex,organization_name,organization_city,organization_country,death_date,death_city,death_country
0,1901,Chemistry,The Nobel Prize in Chemistry 1901,"""in recognition of the extraordinary services ...",1/1,160,Individual,Jacobus Henricus van 't Hoff,1852-08-30,Rotterdam,Netherlands,Male,Berlin University,Berlin,Germany,1911-03-01,Berlin,Germany
1,1901,Literature,The Nobel Prize in Literature 1901,"""in special recognition of his poetic composit...",1/1,569,Individual,Sully Prudhomme,1839-03-16,Paris,France,Male,NaN,NaN,NaN,1907-09-07,Châtenay,France
2,1901,Medicine,The Nobel Prize in Physiology or Medicine 1901,"""for his work on serum therapy, especially its...",1/1,293,Individual,Emil Adolf von Behring,1854-03-15,Hansdorf (Lawice),Prussia (Poland),Male,Marburg University,Marburg,Germany,1917-03-31,Marburg,Germany
3,1901,Peace,The Nobel Peace Prize 1901,NaN,1/2,462,Individual,Jean Henry Dunant,1828-05-08,Geneva,Switzerland,Male,NaN,NaN,NaN,1910-10-30,Heiden,Switzerland
4,1901,Peace,The Nobel Peace Prize 1901,NaN,1/2,463,Individual,Frédéric Passy,1822-05-20,Paris,France,Male,NaN,NaN,NaN,1912-06-12,Paris,France

In [6]:
# checking for null values
nobel.isna().sum()

year                      0
category                  0
prize                     0
motivation               88
prize_share               0
laureate_id               0
laureate_type             0
full_name                 0
birth_date               32
birth_city               36
birth_country            31
sex                      30
organization_name       264
organization_city       265
organization_country    265
death_date              404
death_city              421
death_country           415
dtype: int64

In [11]:
# Filling the null values 
nobel.fillna(0).head()

,year,category,prize,motivation,prize_share,laureate_id,laureate_type,full_name,birth_date,birth_city,birth_country,sex,organization_name,organization_city,organization_country,death_date,death_city,death_country
0,1901,Chemistry,The Nobel Prize in Chemistry 1901,"""in recognition of the extraordinary services ...",1/1,160,Individual,Jacobus Henricus van 't Hoff,1852-08-30,Rotterdam,Netherlands,Male,Berlin University,Berlin,Germany,1911-03-01,Berlin,Germany
1,1901,Literature,The Nobel Prize in Literature 1901,"""in special recognition of his poetic composit...",1/1,569,Individual,Sully Prudhomme,1839-03-16,Paris,France,Male,0,0,0,1907-09-07,Châtenay,France
2,1901,Medicine,The Nobel Prize in Physiology or Medicine 1901,"""for his work on serum therapy, especially its...",1/1,293,Individual,Emil Adolf von Behring,1854-03-15,Hansdorf (Lawice),Prussia (Poland),Male,Marburg University,Marburg,Germany,1917-03-31,Marburg,Germany
3,1901,Peace,The Nobel Peace Prize 1901,0,1/2,462,Individual,Jean Henry Dunant,1828-05-08,Geneva,Switzerland,Male,0,0,0,1910-10-30,Heiden,Switzerland
4,1901,Peace,The Nobel Peace Prize 1901,0,1/2,463,Individual,Frédéric Passy,1822-05-20,Paris,France,Male,0,0,0,1912-06-12,Paris,France

In [21]:
# Most commonly awarded gender and country
top_gender = nobel.value_counts("sex").index[0]
print(top_gender)

top_country = nobel.value_counts("birth_country").index[0]
print(top_country)

Male
United States of America